<?php
// $Id$

/**
 * @file
 * This module provides LDAP-based access control (roles)
 */

define('LDAP_AUTHORIZATION_PROJECT_TAG', 'ldap');

/**
 * Implementation of hook_init().
 */
function ldap_authorization_init() {
}

/**
 * Implementation of hook_theme().
 */
//function ldap_authorization_theme() {
//}


/**
 * Implements hook_ldap_api_permission().
 */
function ldap_authorization_ldap_api_permission() {
  //return ldap_authorization_permission();
}

/**
 * Implements hook_ldap_api_permission().
 */
//function ldap_authorization_permission() {
 // return array('ldap_authorization' =>  'LDAP Authorization: Map LDAP user object properties to drupal roles.');
//}



/**
 * Implementation of hook_menu().
 */
function ldap_authorization_menu() {


  $items[LDAP_API_MENU_BASE_PATH .'/authorization'] = array(
    'title' => t('Authorization'),
    'description' => t('Configure LDAP authorization'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_authorization_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
    'file' => 'ldap_authorization.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_user_role_insert().
 *
 *  Inform other modules that a user role has been added.  (should mark ldap generated roles)
 * 
 */

function ldap_authorization_user_role_insert($role) {
  
}



// vim:fenc=utf-8:ft=php:ai:si:ts=2:sw=2:et:
