<?php

/**
 * @file
 * Install, update and uninstall functions for the LDAP authentication module.
 */

/**
 * Implements hook_install().
 */
function ldap_authentication_install() {

}

/**
 * Implements hook_uninstall().
 */
function ldap_authentication_uninstall() {
  //$result = db_query('DELETE FROM {variables} WHERE name like "ldap_authentication_%"');  
  variable_del('ldap_authentication_conf');
}

