<?php
// $Id$

/**
 * @file
 * This this a temporary placeholder for the main LDAP API module.
 *
 */
define('LDAP_API_CURRENT_API_MODULE', 'ldap_api_temp');




define('LDAP_API_PROJECT_TAG', 'ldap');
define('LDAP_API_API_MODULE_TAG', 'ldap_api');
define('LDAP_API_MENU_BASE_PATH', 'admin/config/people/ldap');
define('LDAP_API_MENU_BASE_PATH_PARTS', 4); // for argument offsets

define('LDAP_API_ENC_TYPE_MD5', 1);
define('LDAP_API_ENC_TYPE_CRYPT', 2);
define('LDAP_API_ENC_TYPE_SALTED_CRYPT', 3);
define('LDAP_API_ENC_TYPE_EXTENDED_DES', 4);
define('LDAP_API_ENC_TYPE_MD5C', 5);
define('LDAP_API_ENC_TYPE_BLOWFISH', 6);
define('LDAP_API_ENC_TYPE_SALTED_MD5', 7);
define('LDAP_API_ENC_TYPE_SHA', 8);
define('LDAP_API_ENC_TYPE_SALTED_SHA', 9);
define('LDAP_API_ENC_TYPE_CLEARTEXT', 10);
define('LDAP_API_CYPHER_MODE', 'cfb', 12);


define('LDAP_SUCCESS',0x00);
define('LDAP_OPERATIONS_ERROR',0x01);
define('LDAP_PROTOCOL_ERROR',0x02);
define('LDAP_TIMELIMIT_EXCEEDED',0x03);
define('LDAP_SIZELIMIT_EXCEEDED',0x04);
define('LDAP_COMPARE_FALSE',0x05);
define('LDAP_COMPARE_TRUE',0x06);
define('LDAP_AUTH_METHOD_NOT_SUPPORTED',0x07);
define('LDAP_STRONG_AUTH_REQUIRED',0x08);
//NotusedinLDAPv3);
define('LDAP_PARTIAL_RESULTS',0x09);

//Next5newinLDAPv3);
define('LDAP_REFERRAL',0x0a);
define('LDAP_ADMINLIMIT_EXCEEDED',0x0b);
define('LDAP_UNAVAILABLE_CRITICAL_EXTENSION',0x0c);
define('LDAP_CONFIDENTIALITY_REQUIRED',0x0d);
define('LDAP_SASL_BIND_INPROGRESS',0x0e);

define('LDAP_NO_SUCH_ATTRIBUTE',0x10);
define('LDAP_UNDEFINED_TYPE',0x11);
define('LDAP_INAPPROPRIATE_MATCHING',0x12);
define('LDAP_CONSTRAINT_VIOLATION',0x13);
define('LDAP_TYPE_OR_VALUE_EXISTS',0x14);
define('LDAP_INVALID_SYNTAX',0x15);

define('LDAP_NO_SUCH_OBJECT',0x20);
define('LDAP_ALIAS_PROBLEM',0x21);
define('LDAP_INVALID_DN_SYNTAX',0x22);

define('LDAP_IS_LEAF',0x23);
define('LDAP_ALIAS_DEREF_PROBLEM',0x24);

define('LDAP_INAPPROPRIATE_AUTH',0x30);
define('LDAP_INVALID_CREDENTIALS',0x31);
define('LDAP_INSUFFICIENT_ACCESS',0x32);
define('LDAP_BUSY',0x33);
define('LDAP_UNAVAILABLE',0x34);
define('LDAP_UNWILLING_TO_PERFORM',0x35);
define('LDAP_LOOP_DETECT',0x36);

define('LDAP_SORT_CONTROL_MISSING',0x3C);
define('LDAP_INDEX_RANGE_ERROR',0x3D);

define('LDAP_NAMING_VIOLATION',0x40);
define('LDAP_OBJECT_CLASS_VIOLATION',0x41);
define('LDAP_NOT_ALLOWED_ON_NONLEAF',0x42);
define('LDAP_NOT_ALLOWED_ON_RDN',0x43);
define('LDAP_ALREADY_EXISTS',0x44/*68*/);
define('LDAP_NO_OBJECT_CLASS_MODS',0x45);
define('LDAP_RESULTS_TOO_LARGE',0x46);
//NexttwoforLDAPv3);
define('LDAP_AFFECTS_MULTIPLE_DSAS',0x47);
define('LDAP_OTHER',0x50);

//UsedbysomeAPIs);
define('LDAP_SERVER_DOWN',0x51);
define('LDAP_LOCAL_ERROR',0x52);
define('LDAP_ENCODING_ERROR',0x53);
define('LDAP_DECODING_ERROR',0x54);
define('LDAP_TIMEOUT',0x55);
define('LDAP_AUTH_UNKNOWN',0x56);
define('LDAP_FILTER_ERROR',0x57);
define('LDAP_USER_CANCELLED',0x58);
define('LDAP_PARAM_ERROR',0x59);
define('LDAP_NO_MEMORY',0x5a);

//PreliminaryLDAPv3codes);
define('LDAP_CONNECT_ERROR',0x5b);
define('LDAP_NOT_SUPPORTED',0x5c);
define('LDAP_CONTROL_NOT_FOUND',0x5d);
define('LDAP_NO_RESULTS_RETURNED',0x5e);
define('LDAP_MORE_RESULTS_TO_RETURN',0x5f);
define('LDAP_CLIENT_LOOP',0x60);
define('LDAP_REFERRAL_LIMIT_EXCEEDED',0x61);



/**
 * Implementation of hook_init().
 */


/**
 * Implementation of hook_perm().
 */
function ldap_api_temp_perm(){
  return array('Admin LDAP Configuration');
}

/**
 * Implement hook_permission().
 */
function ldap_api_temp_permission() {
  return array(
    'administer ldap modules' => array(
      'title' => t('Administer LDAP Configuration') . VERSION,
      'description' => t('dminister LDAP Configuration.'),
      'restrict access' => TRUE,
    ),
  );
}


function ldap_api_temp_menu() {

  $items[LDAP_API_MENU_BASE_PATH] = array(
    'title' => 'LDAP Configuration',
    'description' => 'LDAP authentication, authorization, provisioning, ect.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_api_settings'),
    'access arguments' => array('administer ldap modules'),
    'file' => 'ldap_api.settings.inc',
  );
  
  $items[LDAP_API_MENU_BASE_PATH .'/settings'] = array(
    'title' => '1. Settings',
    'weight' => -2,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}






function ldap_api_ldap_extension_summary($op = 'data') {
  require_once('ldap_api.status.inc');
  return _ldap_api_ldap_extension_summary($op);
}

function ldap_api_ldap_extension_loaded() {
  return extension_loaded('ldap');
}

function ldap_api_encrypt($text, $encryption = NULL) {
  require_once('ldap.encryption.inc');
  return _ldap_api_encrypt($text);
}

function ldap_api_encrypt_types($category = 'all') {
  require_once('ldap.encryption.inc');
  return _ldap_api_encrypt_types($category);
}

function ldap_api_decrypt($encrypted, $encryption = NULL) {
  require_once('ldap.encryption.inc');
  return _ldap_api_decrypt($encrypted, $encryption);
}


