<?php

/**
 * @file
 * This module provides the LDAP package the ability to map drupal profile fields to ldap fields
 */

/**
 * Implements hook_menu().
 */
function ldap_profile_menu() {
  $items = array();

  $items['admin/config/people/ldap/profile'] = array(
    'title' => 'Profile Mapping',
    'description' => 'Configure LDAP Profile Mapping',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_profile_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 7,
    'file' => 'ldap_profile.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_help().
 */

function ldap_profile_help($path, $arg) {
}

/**
 * Implements hook_info().
 */
function ldap_profile_info($field = 0) {
  $info['name']= 'ldap_profile';
  $info['protocol'] = 'LDAP';

  if ($field) {
    return $info[$field];
  }

  return $info;
}

/**
 * Implements hook_user_login().
 */
function ldap_profile_user_login(&$edit, $account) {
  $servers = ldap_servers_get_servers(NULL, 'enabled', TRUE);
  $server = 0;
  $changes = array();
  $authuser = false;
  $ldapuser = false;
  $dn = "";

  foreach ($account->roles as $role) {
    if ($role == 'authenticated user') {
      $authuser = true;
    }
  }

  if (array_key_exists("ldap_authentication", $account->data)) {
    $authdata = $account->data["ldap_authentication"];
    if (array_key_exists('init', $authdata)) {
      $authinit=$authdata['init'];
      foreach ($servers as $s) {
        if ($s->sid == $authinit['sid']) {
          //OK we have found the right server
          $server = $s;
          $ldapuser = true;
          if (array_key_exists('dn', $authinit)) {
            $dn = $authinit['dn'];
          }
        }
      }
    }
  }

  if ($authuser && $ldapuser && $dn != "") {

    $ldapfields = array();
    $mapping = ldap_profile_get_mapping();
    foreach (array_keys($mapping) as $field) {
      if (strpos($field, "field_") !== false) {
        //We have a custom field
        array_push($ldapfields, $mapping[$field]);
      }

    }
    array_push($ldapfields, 'uid');

    $ldapdata = $server->search($dn, "uid=*", $ldapfields);
    var_dump($ldapdata);
    foreach (array_keys($mapping) as $field) {
                 if (strpos($field, "field_") !== false) {
        if (array_key_exists('0', $ldapdata)) {
          if (array_key_exists($mapping[$field], $ldapdata[0])) {
            if (array_key_exists(0, $ldapdata[0][$mapping[$field]])) {
              $add = false;

              if (!property_exists($account, $field)) {
                $add = true;
              }
              else {
                $f = $account->$field;
                if (array_key_exists("und",$f)) {
                  if (array_key_exists("0", $f["und"])) {
                    if (array_key_exists("value", $f["und"][0])) {
                      if ($f["und"][0]["value"] != $ldapdata[0][$mapping[$field]][0]) {
                        $add = true;
                      }
                      elseif (empty($f)) {
                        $add = true;
                      }
                    }
                  }
                }
              }

              if ($add) {
                $changes[$field] = array('und' => array(
                    0 => array(
                      'value' => $ldapdata[0][$mapping[$field]][0]
                      )
                    )
                  );
              }
            }
          }
        }
      }
    }
  }

  if (count($changes) > 0) {
    user_save($account, $changes);
  }
}


/**
 * Implements hook_form_alter().
 */
function ldap_profile_form_alter(&$form, $form_state, $form_id) {

}

/**
 * Provides a valid LdapProfile configuration object.
 */
function ldap_profile_get_valid_conf() {
  static $auth_conf;
  if (is_object($auth_conf)) {
    return $auth_conf;
  }
  require_once('LdapProfileConf.class.php');
  $auth_conf = new LdapProfileConf();
  return ($auth_conf->inDatabase) ? $auth_conf : FALSE;

}

/**
 * Provides a custom tranlation for ldap to drupal information
 * example - ldap stores has a field that specfies supervior = supervisor
 *           in drupal you might want to store this a single on/off checkbox
 *           this will allow you write a data translation for that field
 * @params - field - indicates which ldap field is being translated
 * @params - value - indicates the value from ldap that was pulled
 */
function ldap_profile_translate($field, $value) {
  require_once('ldap_profile_data_translate.inc');
  return ldap_profile_custom_translate($field, $value);
}

/**
 * Provides an array of all the current ldap fields that are currently mapped to profile fields
 */
function ldap_profile_get_ldap_fields() {
  $auth_conf = ldap_profile_get_valid_conf();
  return $auth_conf->ldap_fields;
}

/**
 * Provides an array of all the current profile fields mappings with ldap fields
 */
function ldap_profile_get_mapping($profile_field = '') {
  $auth_conf = ldap_profile_get_valid_conf();
  $result = array();
  $mapping = $auth_conf->mapping;

  if($profile_field != '') {
    if(array_key_exists($profile_field, $mapping)) {
      $result = array($mapping[$profile_field]);
    }
  } else {
    $result = $mapping;
  }
  return $result;
}
