<?php
// $Id: ldap_authorization_drupal_role.install,v 1.2 2010/12/29 01:37:47 johnbarclay Exp $

/**
 * @file
 * Install, update and uninstall functions for the LDAP authorization module.
 */

/**
 * Implementation of hook_install().
 */
function ldap_authorization_drupal_role_install() {

}

/**
 * Implementation of hook_uninstall().
 */
function ldap_authorization_drupal_role_uninstall() {
  

}




