<?php


define('LDAP_SERVERS_PROJECT_TAG', 'ldap');
define('LDAP_SERVERS_MENU_BASE_PATH', 'admin/config/people/ldap');
define('LDAP_SERVERS_MENU_BASE_PATH_PARTS', 4); // for argument offsets
define('LDAP_SERVERS_DRUPAL_HELP_URL', 'http://drupal.org/node/997082');

define('LDAP_SERVERS_ENC_TYPE_MD5', 1);
define('LDAP_SERVERS_ENC_TYPE_CRYPT', 2);
define('LDAP_SERVERS_ENC_TYPE_SALTED_CRYPT', 3);
define('LDAP_SERVERS_ENC_TYPE_EXTENDED_DES', 4);
define('LDAP_SERVERS_ENC_TYPE_MD5C', 5);
define('LDAP_SERVERS_ENC_TYPE_BLOWFISH', 6);
define('LDAP_SERVERS_ENC_TYPE_SALTED_MD5', 7);
define('LDAP_SERVERS_ENC_TYPE_SHA', 8);
define('LDAP_SERVERS_ENC_TYPE_SALTED_SHA', 9);
define('LDAP_SERVERS_ENC_TYPE_CLEARTEXT', 10);
define('LDAP_SERVERS_CYPHER_MODE', 'cfb', 12);


define('LDAP_SUCCESS', 0x00);
define('LDAP_OPERATIONS_ERROR', 0x01);
define('LDAP_PROTOCOL_ERROR', 0x02);
define('LDAP_TIMELIMIT_EXCEEDED', 0x03);
define('LDAP_SIZELIMIT_EXCEEDED', 0x04);
define('LDAP_COMPARE_FALSE', 0x05);
define('LDAP_COMPARE_TRUE', 0x06);
define('LDAP_AUTH_METHOD_NOT_SUPPORTED', 0x07);
define('LDAP_STRONG_AUTH_REQUIRED', 0x08);
//NotusedinLDAPv3);
define('LDAP_PARTIAL_RESULTS', 0x09);

//Next5newinLDAPv3);
define('LDAP_REFERRAL', 0x0a);
define('LDAP_ADMINLIMIT_EXCEEDED', 0x0b);
define('LDAP_UNAVAILABLE_CRITICAL_EXTENSION', 0x0c);
define('LDAP_CONFIDENTIALITY_REQUIRED', 0x0d);
define('LDAP_SASL_BIND_INPROGRESS', 0x0e);

define('LDAP_NO_SUCH_ATTRIBUTE', 0x10);
define('LDAP_UNDEFINED_TYPE', 0x11);
define('LDAP_INAPPROPRIATE_MATCHING', 0x12);
define('LDAP_CONSTRAINT_VIOLATION', 0x13);
define('LDAP_TYPE_OR_VALUE_EXISTS', 0x14);
define('LDAP_INVALID_SYNTAX', 0x15);

define('LDAP_NO_SUCH_OBJECT', 0x20);
define('LDAP_ALIAS_PROBLEM', 0x21);
define('LDAP_INVALID_DN_SYNTAX', 0x22);

define('LDAP_IS_LEAF', 0x23);
define('LDAP_ALIAS_DEREF_PROBLEM', 0x24);

define('LDAP_INAPPROPRIATE_AUTH', 0x30);
define('LDAP_INVALID_CREDENTIALS', 0x31);
define('LDAP_INSUFFICIENT_ACCESS', 0x32);
define('LDAP_BUSY', 0x33);
define('LDAP_UNAVAILABLE', 0x34);
define('LDAP_UNWILLING_TO_PERFORM', 0x35);
define('LDAP_LOOP_DETECT', 0x36);

define('LDAP_SORT_CONTROL_MISSING', 0x3C);
define('LDAP_INDEX_RANGE_ERROR', 0x3D);

define('LDAP_NAMING_VIOLATION', 0x40);
define('LDAP_OBJECT_CLASS_VIOLATION', 0x41);
define('LDAP_NOT_ALLOWED_ON_NONLEAF', 0x42);
define('LDAP_NOT_ALLOWED_ON_RDN', 0x43);
define('LDAP_ALREADY_EXISTS', 0x44);
define('LDAP_NO_OBJECT_CLASS_MODS', 0x45);
define('LDAP_RESULTS_TOO_LARGE', 0x46);
//NexttwoforLDAPv3);
define('LDAP_AFFECTS_MULTIPLE_DSAS', 0x47);
define('LDAP_OTHER', 0x50);

//UsedbysomeAPIs);
define('LDAP_SERVER_DOWN', 0x51);
define('LDAP_LOCAL_ERROR', 0x52);
define('LDAP_ENCODING_ERROR', 0x53);
define('LDAP_DECODING_ERROR', 0x54);
define('LDAP_TIMEOUT', 0x55);
define('LDAP_AUTH_UNKNOWN', 0x56);
define('LDAP_FILTER_ERROR', 0x57);
define('LDAP_USER_CANCELLED', 0x58);
define('LDAP_PARAM_ERROR', 0x59);
define('LDAP_NO_MEMORY', 0x5a);

//PreliminaryLDAPv3codes);
define('LDAP_CONNECT_ERROR', 0x5b);
define('LDAP_NOT_SUPPORTED', 0x5c);
define('LDAP_CONTROL_NOT_FOUND', 0x5d);
define('LDAP_NO_RESULTS_RETURNED', 0x5e);
define('LDAP_MORE_RESULTS_TO_RETURN', 0x5f);
define('LDAP_CLIENT_LOOP', 0x60);
define('LDAP_REFERRAL_LIMIT_EXCEEDED', 0x61);

function ldap_servers_menu() {
  $menu_offset = 4;
  
  $items['admin/config/people/ldap'] = array(
    'title' => 'LDAP Configuration',
    'description' => 'LDAP authentication, authorization, provisioning, ect.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.settings.inc',
  );
  
  $items['admin/config/people/ldap/settings'] = array(
    'title' => '1. Settings',
    'weight' => -2,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  
  $items['admin/config/people/ldap/servers'] = array(
    'title' => '2. Servers',
    'page callback' => 'ldap_servers_edit_index',
    'weight' => -1,
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.admin.inc',
  );

  $items['admin/config/people/ldap/servers/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/config/people/ldap/servers/add'] = array(
    'title' => 'Add LDAP Server Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_admin_form', $menu_offset + 1),
    'type' => MENU_LOCAL_TASK + MENU_IS_LOCAL_ACTION,
    'weight' => 3,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.admin.inc',
  );

  $items['admin/config/people/ldap/servers/test'] = array(
    'title' => 'Test LDAP Server Configuraion',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_test_form', $menu_offset + 1, $menu_offset + 2),
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.test_form.inc',
  );
  
  $items['admin/config/people/ldap/servers/edit'] = array(
    'title' => 'Edit LDAP Server Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_admin_form', $menu_offset + 1, $menu_offset + 2),
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.admin.inc',
  );

$items['admin/config/people/ldap/servers/delete'] = array(
    'title' => 'Delete LDAP Server',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_admin_delete', $menu_offset + 2),
    'type' =>  MENU_CALLBACK +  MENU_LINKS_TO_PARENT + MENU_IS_LOCAL_ACTION,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.admin.inc',
  );  
    
  $items['admin/config/people/ldap/servers/enable'] = array(
    'title' => 'Enable LDAP Server',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_admin_enable_disable', $menu_offset + 1, $menu_offset + 2),
    'type' => MENU_CALLBACK + MENU_LINKS_TO_PARENT + MENU_IS_LOCAL_ACTION,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.admin.inc',
  );   
    
  $items['admin/config/people/ldap/servers/disable'] = array(
    'title' => 'Enable LDAP Server',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ldap_servers_admin_enable_disable', $menu_offset + 1, $menu_offset + 2),
    'type' => MENU_CALLBACK + MENU_LINKS_TO_PARENT + MENU_IS_LOCAL_ACTION,
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_servers.admin.inc',
  );



  return $items;
}



function ldap_servers_theme() {
  return array(
    'ldap_servers_list' => array(
      'variables' => array('ldap_servers' => NULL, 'actions' => TRUE, 'type' => 'table'),
      'render element' => 'element',
      'file' => 'ldap_servers.theme.inc'
    ),
    'ldap_servers_server' => array(
      'variables' => array('ldap_server' => NULL, 'actions' => FALSE, 'type' => 'detail'),
      'render element' => 'element',
      'file' => 'ldap_servers.theme.inc'
    ),
     'ldap_servers_https_required' => array(
      'variables' => array('site_name' => NULL, 'site_mail' => FALSE, 'site_contact_link' => FALSE),
      'render element' => 'element',
      'file' => 'ldap_servers.theme.inc'
    ),     

  );
}

function ldap_servers_cache_clear() {
  $discard = ldap_servers_get_servers(NULL, 'all', FALSE, TRUE);
}
/**
 *
 * return ldap server conf objects
 * 
 * @param alphanum $sid
 * @param enum $type 'all', 'enabled', 
 * @param boolean $flatten signifies if array or single object returned.  Only works if sid is specified
 * @param boolean $reset do not use cached or static result
 * @return array of server conf object keyed on sid or single server conf object (if flatten == TRUE) 
 */
function ldap_servers_get_servers($sid = NULL, $type, $flatten = FALSE, $reset = FALSE) {
  require_once('ldap_servers.inc');
  return _ldap_servers_get_servers($sid, $type, $flatten, $reset);
}

function ldap_servers_fields() {
  require_once('ldap_servers.inc');
  return _ldap_servers_fields();
}

function ldap_servers_get_user_ldap_data($drupal_user, $sid = NULL) {
  require_once('ldap_servers.inc');
  return _ldap_servers_get_user_ldap_data($drupal_user, $sid);
}



function ldap_servers_ldaps_option_array() {
  $options = array();
  $options['none'] = "-- Select LDAP Type --";
  require_once('ldap_servers.functions.inc');
  foreach (ldap_servers_get_ldap_defaults() as $type => $defaults) {
    $options[$type] = $defaults['name'];
  }
  return $options;
}

/**
 * disable a logon form if ldap preferences exclude http logon forms
 * 
 * @param drupal logon form array $form 
 */
function ldap_servers_disable_http_check(&$form) {

  if (variable_get('ldap_servers_require_ssl_for_credentails', 1) == 1 && @$_SERVER['HTTPS'] != 'on') {

    $tokens = array(
      'site_name' => variable_get('site_name', 'this site'),
      'site_mail' =>  variable_get('site_mail', ''),
      );

    $form['#prefix'] = theme('ldap_servers_https_required', $tokens);
    $form['#disabled'] = TRUE;
  } 
}

function ldap_servers_ldap_extension_summary($op = 'data') {
  require_once('ldap_servers.status.inc');
  return _ldap_servers_ldap_extension_summary($op);
}

function ldap_servers_ldap_extension_loaded() {
  return extension_loaded('ldap');
}

function ldap_servers_encrypt($text, $encryption = NULL) {
  require_once('ldap_servers.encryption.inc');
  return _ldap_servers_encrypt($text);
}

function ldap_servers_encrypt_types($category = 'all') {
  require_once('ldap_servers.encryption.inc');
  return _ldap_servers_encrypt_types($category);
}

function ldap_servers_decrypt($encrypted, $encryption = NULL) {
  require_once('ldap_servers.encryption.inc');
  return _ldap_servers_decrypt($encrypted, $encryption);
}

function ldap_servers_no_enabled_servers_msg($action) {

  $servers = ldap_servers_get_servers(NULL, 'enabled');
  if (count($servers) == 0) {

    $message = 'At least one ldap server must configured and <em>enabled</em> before' .
      $action . '. Please go to ' . l('admin/config/people/ldap/servers', 'admin/config/people/ldap/servers') . ' to configure an LDAP server'; 

    drupal_set_message($message, 'warning');
    return $message;
  }
}

function ldap_servers_help($path, $arg) {
  
  $servers_help = t('LDAP Servers stores LDAP server configurations so other modules
    can connect to them and leverage their data.  LDAP authentication and LDAP authorization
    are two such modules.  LDAP Servers is a placeholder module whose functionility will 
    be replaced by LDAP API within the same LDAP project.
    More detailed help is available on drupal.org at !helplink.',
      array(
        '!helplink' => l(LDAP_SERVERS_DRUPAL_HELP_URL, LDAP_SERVERS_DRUPAL_HELP_URL),
      ));
  
  switch ($path) {
    case 'admin/config/people/ldap/servers':
      $output = '<p>' . $servers_help . '</p>';
      return $output;

    case 'admin/help#ldap_servers':
      $output = '<p>' . $servers_help . '</p>';
      return $output;
  }
}



